spring.application.name=secvault-backend
spring.datasource.url=jdbc:sqlserver://lt-sqldb.database.windows.net:1433;database=metasys_training;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.security.user.name=user
spring.security.user.password=password
